Feature to main - portfolio Alex
SniffleSneeze/snifflesneeze.github.io pull request #3
Opened 2021-05-12 13:42 UTC by SniffleSneeze

I do know that I need to update my About me description but I figure I would already ask you your feedback on the work that has been done !!

2021-05-12 14:47 UTC, mporam requested changes

2021-05-12 14:47 UTC, mporam commented on aboutme.html
> +
empty line?

2021-05-12 14:47 UTC, mporam commented on aboutme.html
> +		<link href="./css/normalise.css" type="text/css" rel="stylesheet">
you dont need to use `./` in the href. just doing `css/normalise.css` will work fine

2021-05-12 14:47 UTC, mporam commented on aboutme.html
> +	<header>
all HTML that is displayed on the page should go *inside* the `<body>` tag

2021-05-12 14:47 UTC, mporam commented on aboutme.html
> +					<p>Hey Welcome to my first website !<br>
generally its better to use 2 `<p>` tags than 1 with a `<br>`

2021-05-12 14:47 UTC, mporam commented on aboutme.html
> +				<div class="aboutme-div">
`aboutme-div` isnt a very semantic class name. what if you want to put it on something that isn't a div?

2021-05-12 14:47 UTC, mporam commented on contact.html
> +	<body onclick class="body-image">
`onclick` ?

2021-05-12 14:47 UTC, mporam commented on contact.html
> +
2 empty lines? 1 would be okay, 2 is too many

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +	box-sizing:border-box;
missing spaces after the `:`s

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +	color:white;
colors should always be in hex please

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +
empty line?

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +	border-top:2px solid white;
missing spaces after the `:` and colors should be in hex

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +/*------------------Navbar start here------------------*/
seems unnecessary, the class is literally called navbar

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +	margin-left: auto;
you can do this in less code: `margin: 0 auto;`

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +	background-color:none;
do you need to say no background color? that's default

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +
empty line

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +/*------------------Body Main start here------------------*/
comment seems unnecessary

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +    text-align: center;
indentation is out

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +#index-body-image {
why an ID?

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +	/*overflow:hidden;*/
if you dont need this, remove it from the code

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +	top: 0px;
dont need units on `0` values. 0 is 0 in any unit

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +
extra line break

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +#projet-right {
why an id?

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +#projet-left {
why an id?

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +/*.planet-projet:hover {
please remove

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +
empty lines

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +/*.aboutme:hover {
remove

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +    text-align: center;
incorrect indentation

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +@media only screen and (max-width: 680px){
missing space between `)` and `{`

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +/*------------------------ ABOUT ME PAGE ----------------------------------*/
remove

2021-05-12 14:47 UTC, mporam commented on css/style.css
> +/*------------------------ CONTACT PAGE ----------------------------------*/
remove

2021-05-12 14:47 UTC, mporam commented on index.html
> +<html lang="en" ontouchmove>
`ontouchmove`?

2021-05-12 14:47 UTC, mporam commented on index.html
> +				<a href="./index.html" class="navlink current">Home</a>
dont need the `./`

2021-05-12 14:47 UTC, mporam commented on index.html
> +				<p > Welcome on my Webpage ! have a look around if you have any question, go to the contact tab, I will be please to hear from you</p>
extra space inside the p tag?

2021-05-12 14:47 UTC, mporam commented on index.html
> +	<footer class="container">
footer needs to be inside the body tag

2021-05-12 14:47 UTC, mporam commented on portfolio.html
> +		</nav> <!--Navbar end-->
unnecessary html comments

2021-05-12 14:47 UTC, mporam commented on portfolio.html
> +	<body class="body-image"> <!--body start-->
unnecessary comment

2021-05-12 14:47 UTC, mporam commented on portfolio.html
> +			<div class="planet-projet" id="projet-left" id="p3">
why are you using an id? you cant use the same ID more than once on a page, so technically this is invalid HTML. please use classes

2021-05-12 15:09 UTC, nealioa requested changes

2021-05-12 15:09 UTC, nealioa commented on css/style.css
> +  font-family: arcadeclassic;
Indent is inconsistent with the other rules.

2021-05-12 15:09 UTC, nealioa commented on css/style.css
> +}
Have an empty line after the `}`.

2021-05-12 15:09 UTC, nealioa commented on css/style.css
> +a:active{
Missing a space before `{`.

2021-05-12 15:09 UTC, nealioa commented on css/style.css
> +
Empty line.

2021-05-12 15:09 UTC, nealioa commented on index.html
> +
Unnecessary empty line.

2021-05-12 15:09 UTC, nealioa commented on portfolio.html
> +			<div class="planet-projet" id="projet-left" id="p1">
Two `id`s?
See Mike's comment below.

2021-05-12 15:09 UTC, nealioa commented on portfolio.html
> +			<p>&copy 2021 Alexander Ferreria</p>
HTML entities should end with a semicolon - `&copy;`

2021-05-13 12:21 UTC, mporam requested changes

2021-05-13 12:21 UTC, mporam commented on aboutme.html
> +					<a href="portfolio.html"class="navlink ">Portfolio</a>
missing spaces before the class property

2021-05-13 12:21 UTC, mporam commented on css/style.css
> +	margin: auto auto;
this can just be `margin: auto;`

2021-05-13 12:21 UTC, mporam commented on css/style.css
> +
remove this extra line break

2021-05-13 12:21 UTC, mporam commented on css/style.css
> +	background-color: #00000090;
use rgba for transparency, 8 digit hex doesn't work in all browsers:
https://caniuse.com/css-rrggbbaa

2021-05-13 12:21 UTC, mporam commented on css/style.css
> +	margin-bottom:20px;
missing space after `:`

2021-05-13 12:21 UTC, mporam commented on css/style.css
> +		left: 0%;
dont need `%` on 0 values

2021-05-13 12:34 UTC, mporam approved these changes

2021-05-13 12:40 UTC, merged